In [5]:
#PROBLEM: 1
# CREATE A NULL VECTOR OF SIZE 10 BUT THE FIFTH VALUE WHICH IS 1:

import numpy as np
x = np.zeros(10)
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [6]:
# PROBLEM: 2
# CREATE A VECTOR WITH VALUES RANGING FROM 10 TO 49:
import numpy as np

v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
# PROBLEM: 3
# CREATE A 3*3 MATRIX WITH VALUES RANGING FROM 0 TO 8:
import numpy as np
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# PROBLEM: 4
# FIND INDICES OF NON-ZERO ELEMENTS FROM [1,2,0,0,4,0]
import numpy as np
nums = np.array([1,2,0,0,4,0])
print("Original array: ", nums)
result = np.where(nums !=0)[0]
print("Non-Zero Element Indices is:",result)

Original array:  [1 2 0 0 4 0]
Non-Zero Element Indices is: [0 1 4]


In [7]:
# PROBLEM: 5
# CREATE A 10*10 ARRAY WITH RANDOM VALUES AND FIND THE MINIMUM AND MAXIMUM VALUES: 
import numpy as np
x = np.random.random((10,10))
print(x)
xmin,xmax = x.min(), x.max()
print("Minimum value is: ",xmin)
print("Maximum value is: ",xmax)


[[0.34337647 0.3607224  0.35894823 0.54423648 0.38681176 0.98539888
  0.06779078 0.0849847  0.08811819 0.09127123]
 [0.45990044 0.9769139  0.82538021 0.09874556 0.91165346 0.01852527
  0.17914982 0.09748584 0.41609161 0.62694875]
 [0.8996507  0.24857293 0.49173525 0.58658849 0.00535418 0.09017269
  0.5596649  0.02449765 0.20882989 0.99126266]
 [0.26966156 0.90191704 0.794711   0.34592233 0.29712779 0.20123963
  0.27028345 0.72028055 0.75297888 0.42841713]
 [0.52680926 0.42308629 0.45283076 0.95202228 0.49222138 0.38276834
  0.39960982 0.99728707 0.82226142 0.3714417 ]
 [0.14623889 0.01770601 0.16062204 0.38611901 0.44846621 0.16536065
  0.78091599 0.02832704 0.73060987 0.65413011]
 [0.86557826 0.62919836 0.92158377 0.56713463 0.2391705  0.42265123
  0.45296211 0.95930772 0.1912527  0.06211175]
 [0.36451569 0.51282533 0.47882984 0.664098   0.75131871 0.57848023
  0.16410261 0.85102018 0.15553901 0.9176897 ]
 [0.83000126 0.95100401 0.20652705 0.09451078 0.89178614 0.27247919
  0.86085205

In [6]:
# PROBLEM: 6
# CREATE A RANDOM VECTOR OF SIZE 30 AND FIND THE MEAN VALUE:
import numpy as np
z = np.random.random((30))
print(z)
m = z.mean()
print("Mean Value is: ",m) 

[0.23142824 0.03903126 0.30556435 0.55427756 0.18568637 0.69486929
 0.57732552 0.78492701 0.75754084 0.91162705 0.42538482 0.21765942
 0.78315387 0.6231596  0.18375165 0.860548   0.55442966 0.29792994
 0.98201133 0.66488742 0.48003365 0.87519277 0.47362597 0.16030443
 0.77916477 0.61818494 0.00526163 0.47967877 0.61799805 0.74987335]
Mean Value is:  0.5291503844126991
